MVCWebApplication/Areas/ApplicationSettings/Controllers/StaticSettingsController.cs
using Application.MainBoundedContext.DTO;
using Application.MainBoundedContext.DTO.AdministrationModule;
using DistributedServices.MainBoundedContext.Identity;
using Infrastructure.Crosscutting.Framework.Adapter;
using Infrastructure.Crosscutting.Framework.Utils;
using Microsoft.AspNet.Identity;
using MvcApplication.Controllers;
using MvcApplication.Helpers;
using MvcApplication.Services;
using Presentation.Infrastructure.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using System.Web.Mvc;

namespace MvcApplication.Areas.ApplicationSettings.Controllers
{
    [Authorize(Roles = "Super Administrator")]
    public class StaticSettingsController : BaseController
    {
        private readonly IChannelService _channelService;

        private readonly ServiceHeader serviceHeader;

        private readonly IWebConfigurationService _webConfigurationService;

        private readonly ApplicationUserManager _userManager;

        private readonly ApplicationRoleManager _applicationRoleManager;

        public StaticSettingsController(IChannelService channelService,
            IWebConfigurationService webConfigurationService,
            ApplicationUserManager userManager,
            ApplicationRoleManager roleManager)
        {
            Guard.ArgumentNotNull(channelService, nameof(channelService));

            Guard.ArgumentNotNull(webConfigurationService, nameof(webConfigurationService));

            Guard.ArgumentNotNull(userManager, nameof(userManager));

            Guard.ArgumentNotNull(roleManager, nameof(roleManager));

            _channelService = channelService;

            _webConfigurationService = webConfigurationService;

            serviceHeader = webConfigurationService.GetServiceHeader();

            _userManager = userManager;

            _applicationRoleManager = roleManager;
        }

        // GET: ApplicationSettings/StaticSetting
        public ActionResult Index()
        {
            return View();
        }

        [HttpPost]
        public async Task<JsonResult> StaticSettingList(JQueryDataTablesModel jQueryDataTablesModel)
        {
            int totalRecordCount = 0;

            var currentUser = await _userManager.FindByNameAsync(User.Identity.GetUserName());

            int searchRecordCount = 0;

            var sortAscending = jQueryDataTablesModel.sSortDir_.First() == "asc";

            var sortedColumns = (from s in jQueryDataTablesModel.GetSortedColumns() select s.PropertyName).ToList();

            var pageCollectionInfo = await _channelService.FindSettingFilterInPageAsync(jQueryDataTablesModel.iDisplayStart, jQueryDataTablesModel.iDisplayLength, sortedColumns, jQueryDataTablesModel.sSearch, sortAscending, serviceHeader, 0.75d);

            if (pageCollectionInfo != null && pageCollectionInfo.PageCollection.Any())
            {
                totalRecordCount = pageCollectionInfo.ItemsCount;

                searchRecordCount = !string.IsNullOrWhiteSpace(jQueryDataTablesModel.sSearch) ? pageCollectionInfo.PageCollection.Count : totalRecordCount;

                return this.DataTablesJson(items: pageCollectionInfo.PageCollection, totalRecords: totalRecordCount, totalDisplayRecords: searchRecordCount, sEcho: jQueryDataTablesModel.sEcho);
            }

            return this.DataTablesJson(items: new List<StaticSettingDTO> { }, totalRecords: totalRecordCount, totalDisplayRecords: searchRecordCount, sEcho: jQueryDataTablesModel.sEcho);
        }

        [HttpGet]
        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Create(StaticSettingDTO staticSettingDTO)
        {
            if (!ModelState.IsValid)
            {
                string errorMessage = string.Join(" |", ModelState.Values.SelectMany(a => a.Errors).Select(b => b.ErrorMessage));

                TempData["ModelError"] = staticSettingDTO;

                return View("create", staticSettingDTO);
            }

            var currentUser = await _userManager.FindByNameAsync(User.Identity.GetUserName());

            staticSettingDTO.CreatedBy = currentUser.UserName;

            var checkKeySetting = await _channelService.FindSettingByKeyAsync(staticSettingDTO.Key, serviceHeader);

            if (checkKeySetting != null)
            {
                TempData["Error"] = $"Static setting with the name {staticSettingDTO.Key} already exist!";

                return View(staticSettingDTO);
            }

            staticSettingDTO.CreatedBy = currentUser.UserName;

            var CreateResult = await _channelService.AddNewSettingAsync(staticSettingDTO, serviceHeader);

            if (CreateResult != null)
            {
                TempData["Success"] = "Setting created successfully";

                return RedirectToAction("index", "staticsettings");
            }
            TempData["Error"] = "Setting creation failed.";

            return View("create", staticSettingDTO);
        }

        [HttpGet]
        public async Task<ActionResult> Edit(Guid id)
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity.GetUserName());

            var findresult = await _channelService.FindSettingByIdAsync(id, serviceHeader);

            return View(findresult);
        }

        [HttpPost]
        public async Task<ActionResult> Edit(StaticSettingDTO settingDTO)
        {
            var currentUser = await _userManager.FindByNameAsync(User.Identity.GetUserName());

            if (!ModelState.IsValid)
            {
                string errorMessage = string.Join(" |", ModelState.Values.SelectMany(a => a.Errors).Select(b => b.ErrorMessage));

                TempData["ModelError"] = settingDTO;

                return View("edit", settingDTO);
            }

            settingDTO.CreatedBy = currentUser.UserName;

            var updateresult = await _channelService.UpdateSettingAsync(settingDTO, serviceHeader);

            if (updateresult)
            {
                TempData["Success"] = "setting updated successfully";

                return RedirectToAction("index", "staticsettings");
            }

            TempData["Error"] = "setting update failed. Please try again later";

            return RedirectToAction("index", "staticsettings");
        }

        [HttpGet]
        public async Task<ActionResult> GetStaticSettingDetail(Guid id)
        {
            var staticSetting = await _channelService.FindSettingByIdAsync(id, serviceHeader);

            return View("_staticSettingDetails", staticSetting);
        }
    }
}

MVCWebApplication/Areas/ApplicationSettings/Views/StaticSettings/Create.cshtml
@model Application.MainBoundedContext.DTO.AdministrationModule.StaticSettingDTO
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Error"] != null)
{
    <div class="alert alert-warning fade in">
        <button class="close" data-dismiss="alert">
            ×
        </button>
        <i class="fa-fw fa fa-times"></i>
        <strong>Error!</strong> @TempData["Error"]
    </div>
}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <ol class="breadcrumb">
            <li>
                <a>Home</a>
            </li>
            <li>
                <a>Static Settings</a>
            </li>
            <li class="active">
                <strong>Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Create Static Setting</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("create", "staticsettings",new {Area="ApplicationSettings"},FormMethod.Post, new { id = "form", @class = "wizard-big" }))
                    {
                        @*<form id="form" action="#" class="wizard-big">*@
                        <h1>Setting Details</h1>
                        <fieldset>
                            <h2>Setting Information</h2>
                            <div id="StaticSettingsOriginal" class="row">
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Key, new { @class = "control-label" })
                                        @Html.TextBoxFor(model => model.Key, new { @class = "form-control required" })

                                    </div>
                                </div>
                                <div class="col-sm-3">
                                    <div class="form-group">
                                        @Html.LabelFor(model => model.Value, new { @class = "control-label" })
                                        @Html.TextBoxFor(model => model.Value, new { @class = "form-control required" })
                                    </div>
                                </div>


                            </div>

                        </fieldset>

                        <h1>Confirm Details</h1>
                        <fieldset>
                            <div id="StaticSettingsConfirm">
                            </div>
                        </fieldset>

                        @*</form>*@
                    }
                </div>
            </div>
        </div>

    </div>
</div>

@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/plugins/wizardStepsStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/wizardSteps")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/validate")

    <script type="text/javascript">
        $(document).ready(function () {

            $("#wizard").steps();
            $("#form").steps({
                bodyTag: "fieldset",
                onStepChanging: function (event, currentIndex, newIndex) {
                    // Always allow going backward even if the current step contains invalid fields!
                    if (currentIndex > newIndex) {
                        return true;
                    }

                    // If the current step is the confirmation page run the confirm method
                    if (newIndex === 1) {
                        confirm();
                    }

                    var form = $(this);

                    // Clean up if user went backward before
                    if (currentIndex < newIndex) {
                        // To remove error styles
                        $(".body:eq(" + newIndex + ") label.error", form).remove();
                        $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                    }

                    // Disable validation on fields that are disabled or hidden.
                    form.validate().settings.ignore = ":disabled,:hidden";

                    // Start validation; Prevent going forward if false
                    return form.valid();
                },
                onStepChanged: function (event, currentIndex, priorIndex) {
                    // Suppress (skip) "Warning" step if the user is old enough.
                    if (currentIndex === 2 && Number($("#age").val()) >= 18) {
                        $(this).steps("next");
                    }

                    // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                    if (currentIndex === 2 && priorIndex === 3) {
                        $(this).steps("previous");
                    }
                },
                onFinishing: function (event, currentIndex) {
                    var form = $(this);

                    // Disable validation on fields that are disabled.
                    // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                    form.validate().settings.ignore = ":disabled";

                    // Start validation; Prevent form submission if false
                    return form.valid();
                },
                onFinished: function (event, currentIndex) {
                    var form = $(this);

                    // Submit form input
                    form.submit();
                }
            }).validate({
                errorPlacement: function (error, element) {
                    element.before(error);
                },
                rules: {
                    Key: {
                        required: true,
                        maxlength: 255,
                        minlength: 2
                    }
                }
                //messages: {
                //    Key: {
                //        required: "This field is required",
                //        maxlength: "This field only allows 10 characters",
                //        minlength: "This field require minimumum"
                //    }
                //}
            });

            function confirm() {
                $("#StaticSettingsConfirm").empty();
                $("#StaticSettingsOriginal").clone().appendTo("#StaticSettingsConfirm");

                //get original selects into a jq object
                var $originalSelects = $("#StaticSettingsOriginal").find('select');

                $("#StaticSettingsConfirm").find('select').each(function (index, item) {

                    //set new select to value of old select
                    $(item).val($originalSelects.eq(index).val());

                });
                $("#StaticSettingsConfirm :input").attr("disabled", true);
            }

        });
    </script>
}

MVCWebApplication/Areas/ApplicationSettings/Views/StaticSettings/Edit.cshtml
@model Application.MainBoundedContext.DTO.AdministrationModule.StaticSettingDTO
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <ol class="breadcrumb">
            <li>
                <a>Home</a>
            </li>
            <li>
                <a>Static Settings</a>
            </li>
            <li class="active">
                <strong>Create</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox">
                <div class="ibox-title">
                    <h5>Edit Static Setting</h5>
                </div>
                <div class="ibox-content">
                    @using (Html.BeginForm("edit", "staticsettings",new {Area="ApplicationSettings"},FormMethod.Post, new { id = "form", @class = "wizard-big" }))
                    {
                        @*<form id="form" action="#" class="wizard-big">*@
                        <h1>Setting Details</h1>
                        <fieldset>
                            <h2>Setting Information</h2>
                            <div id="StaticSettingsOriginal" class="row">
                                <div class="row">
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Key, new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.Key, new { @class = "form-control required", disabled = "disabled" })

                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.Value, new { @class = "control-label" })
                                            @Html.TextBoxFor(model => model.Value, new { @class = "form-control required" })
                                        </div>
                                    </div>
                                    <div class="col-sm-3">
                                        <div class="form-group">
                                            @Html.LabelFor(model => model.IsLocked, new { @class = "" })
                                            <br />
                                            @Html.CheckBoxFor(model => model.IsLocked, new { @class = "" })
                                        </div>
                                    </div>

                                </div>
                            </div>
                        </fieldset>

                        <h1>Finish</h1>
                        <fieldset>
                            <div id="StaticSettingsConfirm">
                            </div>
                        </fieldset>
                        @*</form>*@
                    }
                </div>
            </div>
        </div>

    </div>
</div>

@section Styles {
    @Styles.Render("~/Content/plugins/iCheck/iCheckStyles")
    @Styles.Render("~/plugins/wizardStepsStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/wizardSteps")
    @Scripts.Render("~/plugins/iCheck")
    @Scripts.Render("~/plugins/validate")

    <script type="text/javascript">
        $(document).ready(function () {

            $("#wizard").steps();
            $("#form").steps({
                bodyTag: "fieldset",
                onStepChanging: function (event, currentIndex, newIndex) {
                    // Always allow going backward even if the current step contains invalid fields!
                    if (currentIndex > newIndex) {
                        return true;
                    }

                    // If the current step is the confirmation page run the confirm method
                    if (newIndex === 1) {
                        confirm();
                    }


                    var form = $(this);

                    // Clean up if user went backward before
                    if (currentIndex < newIndex) {
                        // To remove error styles
                        $(".body:eq(" + newIndex + ") label.error", form).remove();
                        $(".body:eq(" + newIndex + ") .error", form).removeClass("error");
                    }

                    // Disable validation on fields that are disabled or hidden.
                    form.validate().settings.ignore = ":disabled,:hidden";

                    // Start validation; Prevent going forward if false
                    return form.valid();
                },
                onStepChanged: function (event, currentIndex, priorIndex) {
                    // Suppress (skip) "Warning" step if the user is old enough.
                    if (currentIndex === 2 && Number($("#age").val()) >= 18) {
                        $(this).steps("next");
                    }

                    // Suppress (skip) "Warning" step if the user is old enough and wants to the previous step.
                    if (currentIndex === 2 && priorIndex === 3) {
                        $(this).steps("previous");
                    }
                },
                onFinishing: function (event, currentIndex) {
                    var form = $(this);

                    // Disable validation on fields that are disabled.
                    // At this point it's recommended to do an overall check (mean ignoring only disabled fields)
                    form.validate().settings.ignore = ":disabled";

                    // Start validation; Prevent form submission if false
                    return form.valid();
                },
                onFinished: function (event, currentIndex) {
                    var form = $(this);

                    // Submit form input
                    form.submit();
                }
            }).validate({
                errorPlacement: function (error, element) {
                    element.before(error);
                },
                rules: {
                    Key: {
                        required: true,
                        maxlength: 10,
                        minlength: 2
                    }
                }
                //messages: {
                //    Key: {
                //        required: "This field is required",
                //        maxlength: "This field only allows 10 characters",
                //        minlength: "This field require minimumum"
                //    }
                //}
            });

            function confirm() {
                $("#StaticSettingsConfirm").empty();
                $("#StaticSettingsOriginal").clone().appendTo("#StaticSettingsConfirm");

                //get original selects into a jq object
                var $originalSelects = $("#StaticSettingsOriginal").find('select');

                $("#StaticSettingsConfirm").find('select').each(function (index, item) {

                    //set new select to value of old select
                    $(item).val($originalSelects.eq(index).val());

                });
                $("#StaticSettingsConfirm :input").attr("disabled", true);
            }
        });
    </script>
}

MVCWebApplication/Areas/ApplicationSettings/Views/StaticSettings/Index.cshtml
@using Infrastructure.Crosscutting.Framework.Utils
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@if (TempData["Success"] != null)
{
    <div class="alert alert-success fade in">
        <button class="close" data-dismiss="alert">
            ×
        </button>
        <i class="fa-fw fa fa-check"></i>
        <strong>Success</strong> @TempData["Success"]
    </div>

}
@if (TempData["Error"] != null)
{
    <div class="alert alert-danger fade in">
        <button class="close" data-dismiss="alert">
            ×
        </button>
        <i class="fa-fw fa fa-times"></i>
        <strong>Error !</strong> @TempData["Error"]
    </div>

}
<div class="row wrapper border-bottom white-bg page-heading">
    <div class="col-lg-10">
        <ol class="breadcrumb">
            <li>
                <a>Home</a>
            </li>
            <li>
                <a>Static Settings</a>
            </li>
            <li class="active">
                <strong>Index</strong>
            </li>
        </ol>
    </div>
    <div class="col-lg-2">

    </div>
</div>
<div class="wrapper wrapper-content animated fadeInRight">
    <div class="row m-b-md">
        <div class="col-lg-12">
            <div style="float: left">
                @Html.ActionLink("Create Setting", "Create", "staticsettings", new { Area = "ApplicationSettings" }, new { @class = "btn btn-primary" })

            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-lg-12">
            <div class="ibox float-e-margins">
                <div class="ibox-content">
                    <div class="sk-spinner sk-spinner-wave">
                        <div class="sk-rect1"></div>
                        <div class="sk-rect2"></div>
                        <div class="sk-rect3"></div>
                        <div class="sk-rect4"></div>
                        <div class="sk-rect5"></div>
                    </div>
                    <table id="Grid" class="table table-striped table-bordered table-hover" style="width:100%;">
                        <tbody>
                            <tr>
                                <td colspan="7" class="dataTables_empty">
                                    Loading data from server
                                </td>
                            </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
    <div class="modal fade" id="myModal" role="dialog">
        <div class="modal-dialog" style="width:80%">
            <!-- Modal content-->
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal">
                        &times;
                    </button>
                    <h4 class="modal-title">
                        Static Settings Details
                    </h4>
                </div>
                <div class="modal-body">
                    <span id="test"></span>
                    <div id="detailsDiv">

                    </div>
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-default" data-dismiss="modal">
                        Close
                    </button>
                </div>
            </div>
        </div>
    </div>

</div>

@section Styles {
    @Styles.Render("~/Content/plugins/dataTables/dataTablesStyles")
}

@section Scripts {
    @Scripts.Render("~/plugins/dataTables")

    <script type="text/javascript">
        function LoadSettingDetailsById(id) {
        $.ajax({
            url: '@Url.Action("GetStaticSettingDetail", "StaticSetting",new {Area ="ApplicationSettings"})',
            data: {
                id: id
            },
            dataType: "html",
            type: "GET",
            success: function (data) {

                $("#detailsDiv").html(data);
                $("#SavingsProduct").modal('show');
            }

        });
    }
        $(document).ready(function () {

            $('#Grid').dataTable({
                // Ajax settings
                "sPaginationType": "full_numbers",
                "bProcessing": true,
                "bServerSide": true,
                "sAjaxSource": "@Url.Action("StaticSettingList", "StaticSettings",new {Area ="ApplicationSettings"})",
                 "sServerMethod": "POST",
            // Callback settings
           "fnRowCallback": function (nRow, aData, iDisplayIndex, iDisplayIndexFull) {
               /* row manipulation */

                var createdDate = new Date(parseInt(aData.CreatedDate.replace("/Date(", "").replace(")/", ""), 10));

                var h = ("0" + createdDate.getHours()).slice(-2);
                var m = ("0" + createdDate.getMinutes()).slice(-2);
                var s = ("0" + createdDate.getSeconds()).slice(-2);

                var dt_Created = $.datepicker.formatDate('dd/mm/yy', createdDate) + " " + h + ":" + m + ":" + s;

                $('td:eq(3)', nRow).html(dt_Created);

               var editUrl = '<a class="btn btn-primary" href="staticsettings/edit/' + aData.Id + '">' + 'Edit</a>';

               var viewUrl =
                   '<a class="btn btn-info btn-xs" data-toggle="modal" data-target="#myModal" onclick="GetStaticSettingDetail(\'' +
                   aData.Id +
                   '\')" href="#">' +
                   'View</a>';

               $('td:eq(4)', nRow).html(viewUrl + '&nbsp;|&nbsp;' + editUrl);

               /* return*/
                return nRow;
            },
            // Display settings
            "iDisplayLength": 10,
            "aoColumns": [

                { "mDataProp": "Key", "sTitle": "Key" },
                { "mDataProp": "Value", "sTitle": "Value" },
                { "mDataProp": "IsLocked", "sTitle": "Is Locked ?" },
                { "mDataProp": "CreatedDate", "sTitle": "Created Date" },
                { "mDataProp": "Commands", "sTitle": "Actions", "bSortable": false }
                ],

                "aaSorting": [[0, 'desc']],
                "dom": '<"html5buttons"B>lTfgitp',
                "buttons": [
                    { extend: 'copy' },
                    { extend: 'csv', title: 'Static Settings' },
                    { extend: 'excel', title: 'Static Settings' },

                ],
                "lengthMenu": [[10, 25, 50, 100, 250, 500, 1000], [10, 25, 50, 100, 250, 500, 1000]]
        });

        });
        $(document).ajaxStart(function () {
            $('.ibox').children('.ibox-content').toggleClass('sk-loading');
        });
        $(document).ajaxStop(function () {
            $('.ibox').children('.ibox-content').toggleClass('sk-loading');
        });
    </script>
}

MVCWebApplication/Areas/ApplicationSettings/Views/StaticSettings/_staticSettingDetails.cshtml
@model Application.MainBoundedContext.DTO.AdministrationModule.StaticSettingDTO
@{
    ViewBag.Title = "Wizard";
    Layout = null;
}
<div class="panel-group" id="accordion">
    <div class="panel panel-default">
        <div class="panel-heading" data-toggle="collapse" data-target="#collapseOne">
            <h4 class="panel-title">
                <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">
                    Static Setting Information
                </a>
            </h4>
        </div>
        <div id="collapseOne" class="panel-collapse collapse in">
            <div class="panel-body">
                <div class="row">
                    <div class="col-sm-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Key)
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-check-square"></i></span>
                                @Html.TextBoxFor(model => model.Key, new { @class = "form-control required", disabled = "disabled" })
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.Value)
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-check-square"></i></span>
                                @Html.TextBoxFor(model => model.Value, new { @class = "form-control required", disabled = "disabled" })
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CreatedBy)
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-check-square"></i></span>
                                @Html.TextBoxFor(model => model.CreatedBy, new { @class = "form-control required", disabled = "disabled" })
                            </div>
                        </div>
                    </div>
                    <div class="col-sm-3">
                        <div class="form-group">
                            @Html.LabelFor(model => model.CreatedDate)
                            <div class="input-group">
                                <span class="input-group-addon"><i class="fa fa-check-square"></i></span>
                                @Html.TextBoxFor(model => model.CreatedDate, new { @class = "form-control required", disabled = "disabled" })
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>